baseURL = 'https://glutfeste.github.io/'
languageCode = 'ko-kr'
title = '불타는요새'
theme = 'hugo-book'

# Book 테마를 위한 추가 권장 설정 (선택 사항이지만 시작 시 유용)
# Book 테마의 문서를 보면 더 많은 설정 옵션이 있습니다.
# 예시: https://hugo-book-demo.netlify.app/docs/example-site/
[params]
  # (Optional, default light) Sets color theme: light, dark or auto.
  BookTheme = 'auto' # 'light', 'dark', 'auto' 중 선택 가능
  # (Optional, default true) Controls table of contents visibility on right side of pages.
  BookToC = true
  # (Optional, default docs) Specify section of content to render as menu
  # 기본적으로 content/docs 폴더 내용을 메뉴로 사용합니다.
  # 만약 다른 폴더 (예: content/posts)를 주 메뉴로 쓰고 싶다면 변경 가능
  BookSection = 'docs' # 또는 'posts' 등 원하는 폴더명
  # (Optional, default true) Enables search function with flexsearch
  BookSearch = true
  # (Optional, default true) Enables comments template on pages
  # BookComments = true # 필요하다면 주석 해제 (Disqus 등 연동 필요)

[markup.goldmark.renderer]
  unsafe = true # Shortcodes (예: Mermaid, KaTeX 등) 사용 시 권장

[markup.tableOfContents]
  startLevel = 2
  endLevel = 3
  ordered = false